theme: jekyll-theme-minimal

title: Irvin Tancioco | Electrical Engineering and Computer Science
description: Irvin Tancioco is an electrical engineering and computer science student at the University of California, Berkeley. Irvin is interested to work with the many application of Machine Learning in robotics, VR and art.
